version: '3'

services:
    mysql:
      image: mysql:5.7
      volumes:
        - todo-mysql-data:/var/lib/mysql
      environment: 
      - MYSQL_DATABASE=db_account
      - MYSQL_ROOT_PASSWORD=root
      ports:
         - '3306:3306'
volumes:
  todo-mysql-data:         
     
networks:
  vpc-dev:
    driver:
      bridge